### ISSUE TITLE
Fugu2 hardware: USB-C? 

### ISSUE THREAD

**Issue by samuk** [fl4p/fugu-mppt-firmware#15]
I was wondering if you'd consider doing a version of your Fugu2 hardware that included a USB-C & USB-A socket?

The PD stuff could be stolen from https://oshwlab.com/wagiminator/ip6520-usb-pd-source

Or alternately maybe spin it out as a daughter board?

**Comment by samuk** [comment]
Wrong repo

**Comment by fl4p** [comment]
yes, here's the daughter board with usb type-c connector: https://github.com/open-pe/mcu-head-p12-esp32s3-wroom

it can be mounted with 2.54 SMD pin headers

**Comment by fl4p** [comment]
This little board can be placed on the Fugu2 board instead of the ESP32-S3-WROOM, using SMD pin header.

I currently don't have a rendering or photo to show. Here you can see the footprint of the mounting header to be placed instead of the WROOM:


![image](https://github.com/user-attachments/assets/16733196-e909-4d65-9cee-842e3c406742)

**Comment by fl4p** [comment]
Hi, i was finally able to build the new design
![PXL_20241211_170429248](https://github.com/user-attachments/assets/9a25c5ff-b575-4d32-b60a-3160a745b0bd)

**Comment by fl4p** [comment]
as you can see the esp32-wroom is mounted on a little shield, which has an usb type c plug (not visible on the picture)

i might change the interface for this, so it's compatible with an Esp23s3-zero

![WaveshareESP32-S3-ZeroMS3FH4R2Dual-Core240MHzWi-FiBT5USB-CmitHeader-232463_1920x1920](https://github.com/user-attachments/assets/c8be9721-2e80-41f8-8f4b-6a479cb22156)
